### ISSUE TITLE
Launcher compatibility with an arbitrary console version

### ISSUE THREAD

**Issue by lmakarov** [hechoendrupal/drupal-console-launcher#88]
I have the launcher installed globally and it works fine (reports it's version) outside of a drupal docroot

```
docker@cli:/var/www$ drupal --version
Drupal Console Launcher version 1.0.0-rc14
```

When run in a D8 docroot (without Drupal Console installed in the project) I get the error below, which is expected.

```
docker@cli:/var/www/docroot$ drupal --version

 [ERROR] Drupal Console is not installed at:                                                                            

 You must execute the following composer commands:
                                                                                                                        
 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader                                               
 composer update drupal/console --with-dependencies
```

I then run the commands to get composer installed as a project level dependency:

```
 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader                                               
 composer update drupal/console --with-dependencies
```

Now the launcher is not working inside the docroot:

```
docker@cli:/var/www/docroot$ drupal --version
[03-Mar-2017 16:55:52 UTC] Error: Call to undefined method Drupal\Console\Core\Utils\ConfigurationManager::loadExtendConfiguration() in /var/www/docroot/vendor/drupal/console-core/src/Application.php on line 284 #0 /var/www/docroot/vendor/drupal/console-core/src/Application.php(95): Drupal\Console\Core\Application->registerExtendCommands()
#1 /var/www/docroot/vendor/drupal/console/src/Application.php(49): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(124): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/docroot/vendor/drupal/console/bin/drupal.php(69): Symfony\Component\Console\Application->run()
#4 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(30): include_once('/var/www/docroo...')
#5 phar:///usr/local/bin/drupal/bin/drupal.php(87): Drupal\Console\Launcher\Utils\Launcher->launch('/var/www/docroo...')
#6 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#7 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#8 {main}
Error: Call to undefined method Drupal\Console\Core\Utils\ConfigurationManager::loadExtendConfiguration() in Drupal\Console\Core\Application->registerExtendCommands() (line 284 of /var/www/docroot/vendor/drupal/console-core/src/Application.php).
```

However the installed version of the console if working fine if executed directly:

```
docker@cli:/var/www/docroot$ vendor/bin/drupal --version
Drupal Console version 1.0.0-rc16
```

Notice the versions of the launcher and the console are not the same in my case:

```
Drupal Console Launcher version 1.0.0-rc14
Drupal Console version 1.0.0-rc16
```

If I update the launcher to `1.0.0-rc15` or `1.0.0-rc16`, then everything works as expected.

Presumably the launcher is supposed to be compatible with an arbitrary version of console. Unfortunately the above shows it's not. Unless the `1.0.0-rc14` release of launcher had a regression and this is not something to expect on a regular basis.

**Comment by jmolivas** [comment]
@lmakarov I sent a PR https://github.com/hechoendrupal/drupal-console-launcher/pull/89 removing most of the code for this tool and make it a pure Launcher.

The plan is to have it merged in one or two releases.

**Comment by khananayat** [comment]
update drupal Console Launcher version 1.0.0-rc16 
problem will be resole 
both the version should be be

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/drupal-console-launcher/pull/90 was merged.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
